version: 2.1
orbs: 
  node: circleci/node@2.1.0
jobs:
  build-and-test-client:
    executor: node/default
    steps:
      - checkout
      - run: cd server
      - run: npm install /client/
      - run: cd client; npm test
  build-and-test-server:
    executor: node/default
    steps:
      - checkout
      - run: cd client
      - node/install-packages
      - run: npm test
workflows:
  build-and-test:
   jobs:
    - build-and-test-client
    - build-and-test-server
