version: 2.1
orbs: 
  node: circleci/node@2.1.0
  heroku: circleci/heroku@1.0.1
jobs:
  build-and-test-client:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./client
      - run: 
          name: Testowanie
          command: npm test
          working_directory: ./client
  build-and-test-server:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./server
      - run: 
          name: Testowanie
          command: npm test
          working_directory: ./server
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/deploy-via-git
workflows:
  build-test-and-deploy:
    jobs:
      - deploy:
          requires:
              - build-and-test-client
              - build-and-test-server
          filters:
            only:
              - master
      - build-and-test-client
      - build-and-test-server
      
